### ISSUE TITLE
10-100r3 update to support multiple bibliographic sections

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-ogc#31] opened 2020-02-10 03:31 UTC
Different bibliography sections need to be encoded with `[bibliography]` separately. See: https://www.metanorma.com/author/topics/document-format/bibliography/

```
asciidoctor: ERROR: sources/10-100r3/sections/03-norm-ref.adoc: line 19: bibliography sections do not support nested sections
```

Can a PR be done to this document? Thanks.

**Comment by manuelfuenmayor** [comment] 2020-02-13 19:37
Hi @ronaldtse ,
I believe this is not a "multiple bibliographic section" case because no references are included in the  (unnumbered) subsection. Let me share the capture of the original doc:

![biblio-issue](https://user-images.githubusercontent.com/33627611/74470733-71773780-4e75-11ea-9598-44db951d1586.png)

So, to solve the issue, I removed the markup syntax (`===` ) off the subsection `Recommended Reading` and just leave it boldfaced. I mean, it passed from `=== Recommended Reading` to `*Recommended Reading*`.

PR added in: https://github.com/metanorma/mn-samples-ogc/pull/38

**Comment by ronaldtse** [comment] 2020-02-13 19:40
True. It's a very strange "Recommended Reading" item. I think it should be encoded as a preface section instead of within Normative References? @opoudjis thoughts?

**Comment by manuelfuenmayor** [comment] 2020-02-13 21:13
*For information purposes*
The "Recommend Reading" subsection also includes the following table:

![biblio-issue2](https://user-images.githubusercontent.com/33627611/74478361-a2f6ff80-4e83-11ea-8e12-667cf20c4414.png)
(I didn't share it before because it was in another page.)

**Comment by opoudjis** [comment] 2020-02-28 08:28
The recommended reading semantically is prefatory material, but clearly the expectation here is that it render as past of the normative references. But I don't think we can meet that requirement (which, I have to say, makes little sense.)The problem is that any content in the normative references apart from notes and references is ignored  in rendering, and there is no provision in Asciidoctor for (non-bibliographic) subsections of references.

You have my blessing to move it out of Normative References, and currently both Metanorma and Asciidoc make it awkward to render it there. Whether OGC are happy about moving it out of the Normative References, that's a different question...

**Comment by manuelfuenmayor** [comment] 2020-02-28 13:28
Ok, so I move *Recommended Reading* to another section out of *Normative References*. 
@ronaldtse , do you agree?

**Comment by opoudjis** [comment] 2020-03-09 12:57
@anermina is this relevant to documents you have been editing?

**Comment by anermina** [comment] 2020-03-09 17:34
@opoudjis multiple bibliographic sections weren't needed so far, but there were some documents which included some additional text in the References section. For example, 15-104r5:
![image](https://user-images.githubusercontent.com/55683568/76240944-5e694480-6234-11ea-9509-d88f19226fe7.png)

However, I don't think this is the same case as in Manuel's example.

**Comment by ronaldtse** [comment] 2020-03-29 11:54
@manuel489 , I think we should move the "Recommended Reading" text into a new, last Preface section.

@anermina Let's also move that text into a new, last Preface section.

Once this is done please help close this task. Thanks!

**Comment by manuelfuenmayor** [comment] 2020-03-29 13:13
> @manuel489 , I think we should move the "Recommended Reading" text into a new, last Preface section.

@ronaldtse , @opoudjis has already solved the issue of multiple bibliography section here: https://github.com/metanorma/metanorma-ogc/issues/101

Now we can get a proper result, similar to the original source. Let me show you...

*Original source:*
![original-ogc-capture](https://user-images.githubusercontent.com/33627611/77849878-dfb15880-719c-11ea-84eb-e9a85d49fe89.PNG)

*DOC output:*
![ogc-doc-generated](https://user-images.githubusercontent.com/33627611/77849887-f0fa6500-719c-11ea-8c54-be415eac7292.PNG)

We can even make "Recommended Reading" a legit subsection. For example:

![ogc-doc2-generated](https://user-images.githubusercontent.com/33627611/77849925-269f4e00-719d-11ea-9bb6-9f9c70ef0d8d.PNG)


That been said, do you still want us to move "Recommended Reading" to a new section in the preface?

If your answer is no, would you prefer setting "Recommend Reading" as legit sub-section or boldfaced text?

Thanks!

**Comment by ronaldtse** [comment] 2020-03-29 13:25
@manuel489 yes, we should still move it, because the References section is not supposed to contain anything else other than references. Can you add a comment in the source code that this section used to be in the References section but has been moved to the Preface due to OGC grammar violation? Thanks!

**Comment by manuelfuenmayor** [comment] 2020-03-29 13:30
> @manuel489 yes, we should still move it, because the References section is not supposed to contain anything else other than references. Can you add a comment in the source code that this section used to be in the References section but has been moved to the Preface due to OGC grammar violation? Thanks!

Sure @ronaldtse , I'll be pushing the PR in the next minutes

Thanks!

**Comment by manuelfuenmayor** [comment] 2020-03-29 13:45
PR added in https://github.com/metanorma/mn-samples-ogc/pull/77

**Closed as completed by manuelfuenmayor** 2020-03-29 13:45 UTC
Labels: bug

**Comment by anermina** [comment] 2020-03-29 16:34
> @anermina Let's also move that text into a new, last Preface section.

@ronaldtse , please let me know what should be the title of this section.

**Comment by anermina** [comment] 2020-03-29 16:42
OGC 16-114r3 also has some additional text in References section:
![image](https://user-images.githubusercontent.com/55683568/77854813-bd472b80-71ec-11ea-91fd-c68b6a949acd.png)

**Comment by ronaldtse** [comment] 2020-03-30 01:56
Let's just call it:

```adoc
[.preface]
=== Reference notes
```

**Comment by anermina** [comment] 2020-04-16 13:41
Corrections for the rest of the OGC documents are made in #82.
