### ISSUE TITLE
Issues with 18-046

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-ogc#21] opened 2020-02-05 04:54 UTC
Issues to be handled in markup or metanorma-ogc:

- ~~In chapter 6 (Solutions), tag "elif" is used, but it isn't recognized by Metanorma when rendering. In order to check the output, I've changed this tag to "else" (this renders well), and then reverted change to "elif". Error output:
C:/tools/ruby25/lib/ruby/gems/2.5.0/gems/liquid-4.0.3/lib/liquid/block.rb:38:in `unknown_tag': Liquid syntax error: Unkn
own tag 'elseif' (Liquid::SyntaxError)~~ Fixed in metanorma/metanorma-standoc#200
- Unnumbered tables are shown in the list of tables (I'm not sure if this is fine, since they are untitled).
- Chapters order is different (for the first 3 chapters).
- In .html version, xml codes go out of the margins, i.e. line breaks are not used instead.
- [class=steps] is not working.
- I've mainly used [source,xml] because there are no options available for many code types.
- Warning on the front page has a different content, as well as the License Agreement.
- There should be no "Open Geospatial Consortium OGC 18-046:2020" in the header, and the footer should be different.

**Comment by opoudjis** [comment] 2020-02-05 09:39
First issue now resolved: https://github.com/metanorma/metanorma-standoc/issues/200

**Comment by opoudjis** [comment] 2020-03-03 09:54
> In .html version, xml codes go out of the margins, i.e. line breaks are not used instead.

We have addressed this in https://github.com/metanorma/metanorma-ogc/issues/86

> Chapters order is different (for the first 3 chapters).

In OGC, stop recognising Introduction as part of the preface by default. (Already had to do so for foreword).

> Unnumbered tables are shown in the list of tables (I'm not sure if this is fine, since they are untitled).

I can't replicate this: there are four tables, and all of them are numbered. The contacts list, which is unnumbered, is not in the list of tables; presumably I've already solved this issue.

**Comment by opoudjis** [comment] 2020-03-03 10:09
> Chapters order is different (for the first 3 chapters).

The order is now fixed, but the numbering of the Summary subsections is not i.1 but 1.1. We have not provided for subsections in prefatory sections. I'll note that http://docs.opengeospatial.org/per/18-046.html does not number the Summary as i but as 1.

i containing i.1 not 1.1 is an oversight, easily fixed.

**Comment by opoudjis** [comment] 2020-03-03 10:17
> [class=steps] is not working.

Metanorma defaults to alphabetic ordered lists. We have allowed Arabic numbering in ITU exceptionally, because they are used there for ordered steps; we have not generalised that solution to other flavours. We will impose uniform list numbering in the flavour unless explicitly given criteria to do otherwise; none have been provided for OGC. If OGC want consistent arabic rather than alphabetic ordered steps, we need to be instructed explicitly.

Noted as https://github.com/metanorma/metanorma-ogc/issues/90. Confirmed in metanorma/metanorma-ogc#95

**Comment by opoudjis** [comment] 2020-03-03 12:07
> I've mainly used [source,xml] because there are no options available for many code types.

XML encompasses everything with angle brackets, it was the right choice.

> Warning on the front page has a different content, as well as the License Agreement.

Warning discrepancy needs to be escalated to OGC: the warning adds the sentence "However, the discussions in this document could very well lead to the definition of an OGC Standard", which is not in our boilerplate. 

The license boilerplate adds two paragraphs:

This Agreement is governed by the laws of the Commonwealth of Massachusetts. The application to this Agreement of the United Nations Convention on Contracts for the International Sale of Goods is hereby expressly excluded. In the event any provision of this Agreement shall be deemed unenforceable, void or invalid, such provision shall be modified so as to make it valid and enforceable, and as so modified the entire Agreement shall remain in full force and effect. No decision, action or inaction by LICENSOR shall be construed to be a waiver of any rights or remedies available to it.

None of the Intellectual Property or underlying information or technology may be downloaded or otherwise exported or reexported in violation of U.S. export laws and regulations. In addition, you are responsible for complying with any local laws in your jurisdiction which may impact your right to import, export or use the Intellectual Property, and you represent that you have complied with any regulations or registration procedures required by applicable law to make this license enforceable.

Reported to @ronaldtse to escalate.

Raised as https://github.com/metanorma/metanorma-ogc/issues/91

**Comment by opoudjis** [comment] 2020-03-03 12:12
Do not create contact box in HTML title page for doc types that don't include it.

**Comment by opoudjis** [comment] 2020-03-03 12:24
> There should be no "Open Geospatial Consortium OGC 18-046:2020" in the header, and the footer should be different.

@anermina What should they be instead, and why? The HTML and PDF of the document don't have any header and footer at all, and the Word header and footer are at least consistent.

@ronaldtse You may need to query OGC on what headers and footers they want to see.

**Comment by opoudjis** [comment] 2020-03-03 12:24
Putting this issue on hold, pending resolution with OGC and Nermina.

**Comment by ronaldtse** [comment] 2020-03-03 14:26
@anermina @opoudjis the header/footer issue is now clarified in metanorma/metanorma-ogc#97.

**Comment by opoudjis** [comment] 2020-03-04 00:12
Remaining issue is 

* License boilerplate:  metanorma/metanorma-ogc#91

**Comment by anermina** [comment] 2020-03-04 20:38
Additionally, I've set the element [%unnumbered] before the source codes in #51 .

**Comment by opoudjis** [comment] 2020-03-30 02:14
The license boilerplate issue has been addressed. Therefore, this issue is closed.

**Closed as completed by opoudjis** 2020-03-30 02:14 UTC
Labels: bug
